# Generated by Django 4.2.8 on 2023-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=10, verbose_name='Sex'),
        ),
    ]
