# Generated by Django 4.2.8 on 2024-03-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_detsale_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='price_with_currency',
            field=models.CharField(default='YourDefaultValue', max_length=100),
        ),
    ]
