# Generated by Django 4.2.8 on 2024-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_product_pvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='price_with_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pvp',
        ),
        migrations.AddField(
            model_name='detsale',
            name='price_cop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='price_cop',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
