# Generated by Django 4.2.8 on 2024-03-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_remove_detsale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='price_cop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_cop',
        ),
        migrations.AddField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
