# Generated by Django 4.2.8 on 2024-03-12 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_category_data_updated_category_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sex',
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Naciemiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='identificationCard',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
