# Generated by Django 4.2.8 on 2024-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_sale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
