# Generated by Django 4.2.8 on 2024-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_alter_sale_iva_alter_sale_subtotal_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9, verbose_name='Subtotal'),
        ),
    ]
